# fly.toml file generated for ricochet-robotbot on 2022-11-26T10:54:03-07:00

app = "ricochet-robotbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

